repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [ python ]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
  