version: '3.8'

services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=rexify
      - POSTGRES_PASSWORD=rexify
      - POSTGRES_DB=rexify
    expose:
      - 5432

  backend:
    build:
      context: .
      target: backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://rexify:rexify@db:5432/rexify
    ports:
      - "8001:8001"

  airflow:
    build:
      context: .
      target: airflow
    container_name: airflow
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    depends_on:
      - airflow-db
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"

  # todo: find how to use only one image
  airflow-db:
    image: postgres
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow