version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run sh scripts/lint.sh
            poetry run pytest

  publish:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - run:
          name: Build and publish
          command: |
            poetry build
            poetry version $(git describe --tags --abbrev=0)
            poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD

  build_docker:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker images
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin 
            sh scripts/build_docker.sh

workflows:
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - build_docker:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
