version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  test: 
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pre-install-steps: []
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run pytest

  publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and publish
          command: |
            poetry build
            poetry version $(git describe --tags --abbrev=0)
            poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD

workflows:
  build:
    jobs:
      - test
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
