version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run sh scripts/lint.sh
            poetry run pytest

  publish:
    docker:
      - image: cimg/python:3.8

    steps:
      - run:
          name: Build and publish
          command: |
            poetry build
            poetry version $(git describe --tags --abbrev=0)
            poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

  build_docker:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - setup_remote_docker
      - run:
          name: Build and push Docker images
          command: |
            sh scripts/build.sh

workflows:
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - build_docker:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
