version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pre-install-steps: []
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run pytest

  publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and publish
          command: |
            poetry build
            poetry version $(git describe --tags --abbrev=0)
            poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD

  docker:
    docker:
      - image: cimg/base:2023.04
    environment:
      IMAGE_URI: joseprsm/rexify
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build . -t $IMAGE_URI
      - run:
          name: Push Docker image
          command: | 
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_URI

workflows:
  test_only:
    jobs:
      - test
          
  test_and_build:
    jobs:
      - test:  &tags_only
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish:
          <<: *tags_only
          requires:
            - test
      - request_docker:
          <<: *tags_only
          type: approval
          requires:
            - test
      - docker:
          <<: *tags_only
          requires:
            - request_docker
            - publish
